name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: 初始化pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.30.1

    - name: 初始化node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org/'
        cache: 'pnpm'
    
    - name: 打包/测试
      run: |
        pnpm install --no-frozen-lockfile
        pnpm run build
        pnpm run docs:gen
        pnpm run docs:build
        pnpm run test

    - name: 上传coverage至Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: 发布Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: markdown/.vuepress/dist

    - name: 发布至私有npm仓库
      run: |
        npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}